name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

        - name: MacOS
          os: macos-latest

        #- name: iOS
        #  os: macos-latest
        #  target: iOS

        - name: Android 32-bit
          os: ubuntu-latest
          target: Android32

        - name: Android 64-bit
          os: ubuntu-latest
          target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        if: ${{ matrix.config.target != 'iOS' }}
        uses: geode-sdk/build-geode-mod@main
        with:
          #sdk: nightly # commented because of gd 2.206
          sdk: latest
          bindings-ref: 0554d64fa67e77183a15dcf03145e00f717da631 # here so it can build on 2.205
          combine: true
          target: ${{ matrix.config.target }}
          
      - name: Build the mod (iOS)
        if: ${{ matrix.config.target == 'iOS' }}
        uses: RoootTheFox/build-geode-mod@main
        with:
          sdk: nightly
          combine: true
          target: ${{ matrix.config.target }}

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - uses: RoootTheFox/build-geode-mod/combine@main
        id: build

      - uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}

